search_space:
  optim_wrapper.optimizer.lr:
    _type: loguniform
    _value: [0.0001, 0.1 ]

trial_command: python tools/train.py myconfigs/clip_vit_b32.py
trial_code_directory: .
trial_gpu_number: 2
trial_concurrency: 1
max_trial_number: 10

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  gpuIndices: [1,2]
  use_active_gpu: false